import {test} from "node:test";import assert from "node:assert/strict";import {WorkflowClient} from "../src/workflow-client.ts";
test("should restrict workflow transport and preserve fixed error boundaries",async()=>{
 for(const url of ["http://external.example","https://safe.example/path","https://u:p@safe.example","https://safe.example?key=x"])assert.throws(()=>new WorkflowClient(url),{code:"INVALID_BODY"});for(const url of ["https://safe.example","http://127.0.0.1:4318","http://[::1]:4318","http://localhost:4318"])assert.equal(new WorkflowClient(url).origin,url);
 const prior=globalThis.fetch;const body={protocol:1,agentId:"00000000-0000-4000-8000-000000000001",bindingEpoch:1};const client=new WorkflowClient("http://127.0.0.1:4318");let calls=0;
 try{globalThis.fetch=async(input,init)=>{calls++;assert.equal(String(input),"http://127.0.0.1:4318/api/workflow/poll");assert.equal(init?.redirect,"error");assert.ok(init?.signal);assert.equal(new Headers(init?.headers).get("authorization"),`Bearer ${"a".repeat(64)}`);throw new Error("provider secret native-session");};await assert.rejects(client.call("poll",body,"a".repeat(64)),{message:"UNAVAILABLE"});assert.equal(calls,1);
 globalThis.fetch=async()=>new Response(JSON.stringify({ok:false,error:{code:"CONFLICT"}}),{status:409,headers:{"Content-Type":"application/json"}});await assert.rejects(client.call("poll",body,"a".repeat(64)),{code:"CONFLICT"});
 for(const response of [new Response(JSON.stringify({ok:false,error:{code:"CONFLICT",message:"secret"}}),{status:409,headers:{"Content-Type":"application/json"}}),new Response(JSON.stringify({ok:true,data:{nativeSession:"secret"}}),{headers:{"Content-Type":"application/json"}}),new Response("a".repeat(65537),{headers:{"Content-Type":"application/json"}}),new Response(null,{status:302,headers:{Location:"http://external.example"}})]){globalThis.fetch=async()=>response;await assert.rejects(client.call("poll",body,"a".repeat(64)),{code:"UNAVAILABLE"});}await assert.rejects(client.call("poll",{...body,rawPrompt:"bad"},"a".repeat(64)),{code:"INVALID_BODY"});
 }finally{globalThis.fetch=prior;}
});
