import {randomUUID,timingSafeEqual} from "node:crypto";
import {open,rename,rm,lstat} from "node:fs/promises";import {constants} from "node:fs";import {join} from "node:path";import {createServer} from "node:http";import type {AddressInfo} from "node:net";import {spawn} from "node:child_process";
import {DeviceFixture,assertDeviceMigrationSources,secret,type DeviceProfile,type DeviceResponse} from "./device-binding-fixture.js";
import {assertOwnedStack,productEnvironment,ensure,type FixturePerson} from "./local-access-stack.js";
import {authBrowserChildEnvironment} from "./auth-browser-artifact-policy.js";
import {projectEnvelope,validateBody,type Action,type HumanAction,type DeviceAction,type Body,type HistoryPage,type AttemptSnapshot,type CycleAdmission,type PollSnapshot,type TerminalReceipt} from "../../src/features/investigation-coordinator/contracts.js";
export type WorkflowScene={scope:{organizationId:string;roomId:string};owner:FixturePerson;peer:FixturePerson;observer:FixturePerson;outsider:FixturePerson;origin:DeviceProfile;responder:DeviceProfile};
function safe(error:unknown,stage:string){const frame=error instanceof Error?error.stack?.match(/\/(investigation-coordinator\.test|workflow-fixture)\.(?:js|ts):(\d+):(\d+)/):null;return new Error(`Owned workflow ${stage} failed${frame?` at ${frame[1]}:${frame[2]}:${frame[3]}`:""}; private diagnostics withheld`);}
export class WorkflowFixture {
 readonly rooms=new Map<string,string>();readonly identities=new Map<string,Set<string>>();readonly operations:{roomId:string;actorId:string;action:Action;operationId:string}[]=[];private writes:Promise<void>=Promise.resolve();private actorKinds=new Map<string,"human"|"device">();
 private constructor(readonly devices:DeviceFixture){const previous=devices.stack.onOwnedIdentity;devices.stack.onOwnedIdentity=async()=>{await previous?.();await this.save();};}
 get stack(){return this.devices.stack;}
 static async open(label:string){await assertDeviceMigrationSources();const devices=await DeviceFixture.open(`workflow-${label}`);try{const installed=await devices.stack.db.query("select to_regclass('workflow_private.attempts') is not null installed,to_regprocedure('public.workflow_device_claim(jsonb,text)') is not null claim");ensure(installed.rows[0].installed&&installed.rows[0].claim,"Workflow migration requires supervising installation");const f=new WorkflowFixture(devices);await f.save();return f;}catch(e){await devices.close();throw safe(e,"setup");}}
 async save(){const pending=this.writes.then(async()=>{await this.devices.saveCleanupIdentity();const file=join(this.devices.root,"workflow-identity.json");try{const s=await lstat(file);ensure(s.isFile()&&!s.isSymbolicLink()&&s.nlink===1&&(s.mode&0o777)===0o600,"Unsafe workflow identity");}catch(e){if((e as NodeJS.ErrnoException).code!=="ENOENT")throw e;}const identity={version:1,namespace:this.stack.namespace,project:this.stack.config.project,rooms:[...this.rooms].map(([id,organizationId])=>({id,organizationId})),users:[...this.stack.users],organizations:[...this.stack.organizationOwners].map(([id,ownerUserId])=>({id,ownerUserId})),bindings:[...this.devices.profiles.values()].map(p=>({name:p.name,deviceId:p.deviceId,agentId:p.agentId,ownerUserId:p.ownerUserId,roomId:p.roomId})),records:Object.fromEntries([...this.identities].map(([k,v])=>[k,[...v]])),operations:this.operations};const temporary=join(this.devices.root,`.workflow-${randomUUID()}.tmp`);let handle;try{handle=await open(temporary,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_NOFOLLOW,0o600);await handle.writeFile(JSON.stringify(identity));await handle.sync();await handle.close();handle=undefined;await rename(temporary,file);const parent=await open(this.devices.root,constants.O_RDONLY|constants.O_DIRECTORY|constants.O_NOFOLLOW);try{await parent.sync();}finally{await parent.close();}}finally{await handle?.close();await rm(temporary,{force:true});}});this.writes=pending.catch(()=>{});return pending;}
 private capture(value:unknown){if(!value||typeof value!=="object")return;for(const [k,v] of Object.entries(value)){if(["cycleId","requestId","attemptId","eventId","questionId","controlId","continuationRequestId","peerRequestId"].includes(k)&&typeof v==="string"){const key=k==="continuationRequestId"||k==="peerRequestId"?"requestId":k;const ids=this.identities.get(key)??new Set();ids.add(v);this.identities.set(key,ids);}else if(v&&typeof v==="object")this.capture(v);}}
 async scene(label="main"):Promise<WorkflowScene>{const owner=await this.stack.person(`${label}-owner`),peer=await this.stack.person(`${label}-peer`),observer=await this.stack.person(`${label}-observer`),outsider=await this.stack.person(`${label}-outsider`);const scope=await this.stack.bootstrap(owner);this.rooms.set(scope.roomId,scope.organizationId);await this.save();await this.stack.join(peer,await this.stack.invite(owner,scope.roomId),"질문 참가자");await this.stack.join(observer,await this.stack.invite(owner,scope.roomId,"observer"),"관찰자");const origin=await this.devices.register(await this.devices.connected(owner,scope,`${label}-origin`));const responder=await this.devices.register(await this.devices.connected(peer,scope,`${label}-peer`));await this.ready(origin);await this.ready(responder);return {scope,owner,peer,observer,outsider,origin,responder};}
 async human(person:FixturePerson,action:HumanAction,fields:Body):Promise<DeviceResponse>{ensure(this.stack.users.has(person.id)&&this.rooms.has(String(fields.roomId)),"Unowned workflow request");this.actorKinds.set(person.id,"human");const body=validateBody(action,{protocol:1,...fields});if(action!=="read")this.operations.push({roomId:String(body.roomId),actorId:person.id,action,operationId:String(body.operationId)});await this.save();const response=await person.web.post(`/api/investigations/${action}`,body);const text=await response.text();const data=JSON.parse(text);if(response.status===200){projectEnvelope(action,data,response.status);this.capture(data);await this.save();}return {status:response.status,headers:response.headers,text,data};}
 async device(p:DeviceProfile,action:DeviceAction,fields:Body={},credential=p.credential):Promise<DeviceResponse>{ensure(this.devices.profiles.get(p.name)===p&&p.roomId&&this.rooms.has(p.roomId),"Unowned workflow binding");this.actorKinds.set(p.deviceId!,"device");const body=validateBody(action,{protocol:1,agentId:p.agentId!,bindingEpoch:await this.epoch(p),...fields});if(action!=="poll")this.operations.push({roomId:p.roomId,actorId:p.deviceId!,action,operationId:String(body.operationId)});await this.save();const response=await fetch(`${this.stack.config.app}/api/workflow/${action}`,{method:"POST",redirect:"error",signal:AbortSignal.timeout(10000),headers:{"Content-Type":"application/json",Authorization:`Bearer ${credential}`},body:JSON.stringify(body)});const text=await response.text();const data=JSON.parse(text);if(response.status===200){projectEnvelope(action,data,response.status);this.capture(data);await this.save();}return {status:response.status,headers:response.headers,text,data};}
 async epoch(p:DeviceProfile){ensure(p.agentId&&this.devices.profiles.get(p.name)===p,"Unowned epoch lookup");const row=await this.stack.db.query("select binding_epoch from device_binding_private.agents where id=$1 and device_id=$2 and room_id=$3",[p.agentId,p.deviceId,p.roomId]);return Number(row.rows[0]?.binding_epoch??1);}
 async ready(p:DeviceProfile,reportedReady=true,operationId=randomUUID()){return this.device(p,"ready",{operationId,reportedReady});}
 async read(s:WorkflowScene,person=s.owner,afterSequence=0){const response=await this.human(person,"read",{roomId:s.scope.roomId,afterSequence});ensure(response.status===200,"Workflow read failed");return response.data.data as HistoryPage;}
 async history(s:WorkflowScene,person=s.owner){let cursor=0;const events:HistoryPage["events"]=[];let page:HistoryPage;do{page=await this.read(s,person,cursor);events.push(...page.events);ensure(page.nextCursor>=cursor,"History cursor moved backwards");cursor=page.nextCursor;}while(page.hasMore);return {...page,events};}
 async start(s:WorkflowScene,operationId=randomUUID()){const history=await this.read(s);const response=await this.human(s.owner,"start",{roomId:s.scope.roomId,operationId,originAgentId:s.origin.agentId!,peerAgentId:s.responder.agentId!,originEpoch:await this.epoch(s.origin),peerEpoch:await this.epoch(s.responder),expectedRoomRevision:history.roomRevision,publicText:"합성 공개 조사",confirmed:true});ensure(response.status===200,"Workflow start failed");return response.data.data as CycleAdmission;}
 async poll(p:DeviceProfile){const r=await this.device(p,"poll");ensure(r.status===200,"Workflow poll failed");return r.data.data as PollSnapshot;}
 async claim(p:DeviceProfile,requestId:string){await this.ready(p);const r=await this.device(p,"claim",{operationId:randomUUID(),requestId});ensure(r.status===200,"Workflow claim failed");return r.data.data as AttemptSnapshot;}
 identity(a:AttemptSnapshot){return {operationId:randomUUID(),requestId:a.requestId,attemptId:a.attemptId,fence:a.fence};}
 async intent(p:DeviceProfile,a:AttemptSnapshot){const r=await this.device(p,"start-intent",this.identity(a));ensure(r.status===200,"Start intent failed");return r.data.data as AttemptSnapshot;}
 async run(p:DeviceProfile,requestId:string){return this.intent(p,await this.claim(p,requestId));}
 async question(p:DeviceProfile,a:AttemptSnapshot){const r=await this.device(p,"question",{...this.identity(a),publicText:"합성 공개 질문",confirmed:true});ensure(r.status===200,"Addressed question failed");return r.data.data as {cycleId:string;questionId:string|null;peerRequestId:string|null;accepted:boolean;cycleState:string};}
 async complete(p:DeviceProfile,a:AttemptSnapshot,terminal:"COMPLETED"|"FAILED"|"INTERRUPTED"="COMPLETED",publicText="합성 공개 결과"){const r=await this.device(p,"complete",{...this.identity(a),terminal,publicText:terminal==="COMPLETED"?publicText:""});ensure(r.status===200,"Terminal report failed");return r.data.data as TerminalReceipt;}
 async expire(kind:"readiness"|"lease"|"cycle"|"question",id:string){await assertOwnedStack(this.stack.config);ensure([...this.stack.users].every(u=>u.length===36),"Invalid fixture identity");await this.save();const query=kind==="readiness"?"select rd.agent_id id,rd.room_id from workflow_private.readiness rd join device_binding_private.agents a on a.id=rd.agent_id where rd.agent_id=$1 and a.owner_user_id=any($2::uuid[])":kind==="lease"?"select a.id,q.room_id from workflow_private.attempts a join workflow_private.requests q on q.id=a.request_id where a.id=$1 and q.owner_id=any($2::uuid[])":kind==="cycle"?"select id,room_id from workflow_private.cycles where id=$1 and origin_owner_id=any($2::uuid[])":"select q.id,c.room_id from workflow_private.questions q join workflow_private.cycles c on c.id=q.cycle_id where q.id=$1 and c.origin_owner_id=any($2::uuid[])";const owned=await this.stack.db.query(query,[id,[...this.stack.users]]);ensure(owned.rowCount===1&&this.rooms.has(owned.rows[0].room_id),"Refusing an unowned timestamp");const key=kind==="readiness"?"agentId":kind==="lease"?"attemptId":kind==="cycle"?"cycleId":"questionId";ensure(kind==="readiness"?[...this.devices.profiles.values()].some(p=>p.agentId===id):this.identities.get(key)?.has(id),"Timestamp identity was not recorded");const statements={readiness:"update workflow_private.readiness set valid_until=clock_timestamp()-interval '1 second' where agent_id=$1 and room_id=$2",lease:"update workflow_private.attempts set lease_expires_at=clock_timestamp()-interval '1 second' where id=$1 and request_id in (select id from workflow_private.requests where room_id=$2)",cycle:"update workflow_private.cycles set deadline=clock_timestamp()-interval '1 second' where id=$1 and room_id=$2",question:"update workflow_private.questions set deadline=clock_timestamp()-interval '1 second' where id=$1 and cycle_id in (select id from workflow_private.cycles where room_id=$2)"};await this.stack.db.query(statements[kind],[id,owned.rows[0].room_id]);}
 async count(roomId:string){ensure(this.rooms.has(roomId),"Unowned workflow count");const r=await this.stack.db.query("select (select count(*)::int from workflow_private.requests where room_id=$1) requests,(select count(*)::int from workflow_private.attempts a join workflow_private.requests r on r.id=a.request_id where r.room_id=$1) attempts,(select count(*)::int from public.workflow_events where room_id=$1) events,(select sum(runs_reserved)::int from workflow_private.cycles where room_id=$1) budget",[roomId]);return r.rows[0] as {requests:number;attempts:number;events:number;budget:number|null};}
 async recoverOperations(){await assertOwnedStack(this.stack.config);for(const op of this.operations){const organizationId=this.rooms.get(op.roomId);ensure(organizationId&&this.stack.organizations.has(organizationId),"Unowned operation recovery scope");const human=["speak","start","interrupt","pause","resume"].includes(op.action);ensure(this.actorKinds.get(op.actorId)===(human?"human":"device"),"Unowned operation recovery actor");const found=await this.stack.db.query("select x.result from workflow_private.receipts x join public.rooms r on r.id=x.room_id where x.room_id=$1 and r.organization_id=$2 and x.actor_id=$3 and x.actor_kind=$4 and x.operation_id=$5 and x.action=$6",[op.roomId,organizationId,op.actorId,human?"human":"device",op.operationId,op.action]);for(const row of found.rows)this.capture(row.result);}await this.save();}
 async close(){const failures:Error[]=[];try{await this.recoverOperations();await this.save();}catch(e){failures.push(safe(e,"recovery"));}try{await this.devices.close();}catch(e){failures.push(safe(e,"cleanup"));}if(failures.length)throw new AggregateError(failures,"Owned workflow cleanup failed; private diagnostics withheld");}
}
export async function workflowCase(label:string,run:(f:WorkflowFixture)=>Promise<void>){let f:WorkflowFixture|undefined;const failures:Error[]=[];try{f=await WorkflowFixture.open(label);await run(f);}catch(e){failures.push(safe(e,"assertion"));}try{await f?.close();}catch(e){failures.push(safe(e,"cleanup"));}if(failures.length)throw new AggregateError(failures,"Owned workflow check failed; private diagnostics withheld");}
export async function runWorkflowBrowserParent(){const fixture=await WorkflowFixture.open("browser");const token=secret();const scenes=new Map<string,WorkflowScene>();const people=new Map<string,FixturePerson>();const active=new Map<string,AttemptSnapshot>();const steps=new Map<string,Set<string>>();
 const server=createServer(async(req,res)=>{try{ensure(req.method==="POST"&&typeof req.headers.authorization==="string","Invalid broker request");const got=Buffer.from(req.headers.authorization.slice(7)),expected=Buffer.from(token);ensure(req.headers.authorization.startsWith("Bearer ")&&got.length===expected.length&&timingSafeEqual(got,expected),"Invalid broker authority");let size=0;const chunks:Buffer[]=[];for await(const part of req){size+=part.length;ensure(size<=4096,"Oversized broker request");chunks.push(part);}const input=JSON.parse(Buffer.concat(chunks).toString()) as Record<string,string>;let data:unknown;
 if(req.url==="/setup"){ensure(Object.keys(input).length===1&&/^(?:desktop|mobile)-(?:history|control)$/.test(input.scene)&&!scenes.has(input.scene),"Invalid fixed scene");const s=await fixture.scene(input.scene);scenes.set(input.scene,s);steps.set(input.scene,new Set());for(const p of [s.owner,s.peer,s.observer])people.set(p.id,p);data={roomId:s.scope.roomId,owner:{id:s.owner.id,email:s.owner.email},observer:{id:s.observer.id,email:s.observer.email}};}
 else if(req.url==="/code"){ensure(Object.keys(input).length===1&&people.has(input.id),"Unowned broker person");const p=people.get(input.id)!;data={code:await fixture.stack.code(p.email)};}
 else if(req.url==="/drive"){ensure(Object.keys(input).length===2&&scenes.has(input.scene)&&["history","start","ack","unknown","terminal"].includes(input.step),"Invalid fixed driver step");const seen=steps.get(input.scene)!;ensure(!seen.has(input.step)&&((input.scene.endsWith("-history")&&input.step==="history")||(input.scene.endsWith("-control")&&((input.step==="start"&&seen.size===0)||(input.step==="ack"&&seen.has("start")&&!seen.has("unknown"))||(input.step==="unknown"&&seen.has("start"))||(input.step==="terminal"&&seen.has("unknown"))))),"Invalid bounded driver transition");seen.add(input.step);const s=scenes.get(input.scene)!;if(input.step==="history"||input.step==="start"){await fixture.ready(s.origin);await fixture.ready(s.responder);}if(input.step==="history"){const admitted=await fixture.start(s);const a=await fixture.run(s.origin,admitted.requestId!);const q=await fixture.question(s.origin,a);const p=await fixture.run(s.responder,q.peerRequestId!);await fixture.complete(s.origin,a,"COMPLETED","합성 공개 origin 결과");const done=await fixture.complete(s.responder,p);const continuation=await fixture.run(s.origin,done.continuationRequestId!);await fixture.complete(s.origin,continuation,"COMPLETED","합성 공개 최종 결과");data={state:"COMPLETED",verification:"reported"};}else if(input.step==="start"){const admitted=await fixture.start(s);active.set(input.scene,await fixture.run(s.origin,admitted.requestId!));data={state:"RUNNING",verification:"reported"};}else{const a=active.get(input.scene);ensure(a,"No owned fixed run");if(input.step==="ack"){const poll=await fixture.poll(s.origin);ensure(poll.control,"No owned control");await fixture.device(s.origin,"interrupt-ack",{...fixture.identity(a),controlId:poll.control.controlId});data={state:"ACKNOWLEDGED"};}else if(input.step==="unknown"){await fixture.expire("lease",a.attemptId);await fixture.poll(s.origin);data={state:"UNKNOWN"};}else{const poll=await fixture.poll(s.origin);if(poll.control)await fixture.device(s.origin,"interrupt-ack",{...fixture.identity(a),controlId:poll.control.controlId});const result=await fixture.device(s.origin,"observe",{...fixture.identity(a),terminal:"INTERRUPTED",publicText:""});ensure(result.status===200,"Owned terminal failed");data={state:"INTERRUPTED"};}}}
 else throw new Error("Invalid workflow broker path");res.writeHead(200,{"Content-Type":"application/json","Cache-Control":"no-store"}).end(JSON.stringify(data));}catch{res.writeHead(500,{"Content-Type":"application/json"}).end('{"error":"Owned workflow broker failed"}');}});
 try{await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));const env={...productEnvironment(),LOCAL_WORKFLOW_FIXTURE_URL:`http://127.0.0.1:${(server.address() as AddressInfo).port}`,LOCAL_WORKFLOW_FIXTURE_TOKEN:token,...authBrowserChildEnvironment};const child=spawn(process.execPath,["node_modules/@playwright/test/cli.js","test","--config","playwright.workflow.config.ts"],{env,stdio:"inherit"});process.exitCode=await new Promise<number>(r=>{child.on("exit",c=>r(c??1));child.on("error",()=>r(1));});}finally{await new Promise<void>(r=>server.close(()=>r()));await fixture.close();}
}
if(process.argv.includes("--workflow-e2e-runner"))runWorkflowBrowserParent().catch(()=>{process.stderr.write("Owned workflow browser setup failed; private diagnostics withheld\n");process.exitCode=1;});
